// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI3JEevJ5JHmuzw3oKLq6hk9o_fQHS95k',
    appId: '1:546690347510:web:4943511f50a0e400cd97d7',
    messagingSenderId: '546690347510',
    projectId: 'hackathon24-d3077',
    authDomain: 'hackathon24-d3077.firebaseapp.com',
    storageBucket: 'hackathon24-d3077.appspot.com',
    measurementId: 'G-VPWMYZFXT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpr4hanmWbrjkum-f-db2y1DYjyiO6k2w',
    appId: '1:546690347510:android:01ad64842e8bc4eacd97d7',
    messagingSenderId: '546690347510',
    projectId: 'hackathon24-d3077',
    storageBucket: 'hackathon24-d3077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWz2a4U9CW2wBdMzcUyUsuOos44n2Y328',
    appId: '1:546690347510:ios:db07927c38333cc0cd97d7',
    messagingSenderId: '546690347510',
    projectId: 'hackathon24-d3077',
    storageBucket: 'hackathon24-d3077.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWz2a4U9CW2wBdMzcUyUsuOos44n2Y328',
    appId: '1:546690347510:ios:db07927c38333cc0cd97d7',
    messagingSenderId: '546690347510',
    projectId: 'hackathon24-d3077',
    storageBucket: 'hackathon24-d3077.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI3JEevJ5JHmuzw3oKLq6hk9o_fQHS95k',
    appId: '1:546690347510:web:da5deb5ae91cc785cd97d7',
    messagingSenderId: '546690347510',
    projectId: 'hackathon24-d3077',
    authDomain: 'hackathon24-d3077.firebaseapp.com',
    storageBucket: 'hackathon24-d3077.appspot.com',
    measurementId: 'G-4JSPWLCDP6',
  );
}
